# Generated by Django 3.1.6 on 2021-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
